Repository DiversityCorp/companies-on-blm, pull requests merged in 2020-10, with the labels that each got.

#32 Changed all occurrences of 'forbes_rank' to 'fortune_rank'
  companies/amazon.md
  companies/amerisource-bergen.md
  companies/apple.md
  companies/att.md
  companies/berkshire-hathaway.md
  companies/chevron.md
  companies/cvs-health.md
  companies/exxon-mobile.md
  companies/fordmotor.md
  companies/mckesson.md
  companies/unitedhealth-group.md
  companies/walmart.md
  examples/add-a-company.md
Labels: hacktoberfest-accepted

#30 costco.md file created
  companies/costco.md
Labels: hacktoberfest-accepted

#42 initial database creation script and instructions
  db/DiversityCorp.sql
  db/create-the-database-heroku.md
Labels: hacktoberfest-accepted

#43 Added data for fortune 21-30 companies
  data/Fortune21-30/Basic_Anjali001_14Oct20.csv
  data/Fortune21-30/Events_Anjali001_14Oct20.csv
  data/Fortune21-30/Financial_Anjali001_14Oct20.csv
  data/Fortune21-30/HR_Anjali001_14Oct20.csv
  data/Fortune21-30/Ranking_Anjali001_14Oct20.csv
Labels: hacktoberfest-accepted

#56 Added data for Redfin
  companies/redfin.md
Labels: hacktoberfest-accepted

#59 Added Netflix to companies
  companies/netflix.md
Labels: hacktoberfest-accepted

#94 Create github.md
  companies/github.md
Labels: hacktoberfest-accepted

#96 Added Salesforce issue 87
  companies/salesforce.md
Labels: hacktoberfest-accepted

#98 Added Cisco issue 83
  companies/cisco.md
Labels: hacktoberfest-accepted

#99 Added Twilio data
  companies/twilio.md
Labels: hacktoberfest-accepted

#101 Fixed error on Salesforce page
  companies/cisco.md
  companies/salesforce.md
Labels: bug, hacktoberfest-accepted

#102 Added PlayStation data
  companies/playstation.md
Labels: hacktoberfest-accepted

#105 Create google.md
  companies/google.md
Labels: hacktoberfest-accepted

#92 added ben & jerry info
  companies/ben-jerrys.md
Labels: hacktoberfest-accepted

#111 Redesign company cards
  _includes/layouts/base.njk
  statements.njk
  style.css
Labels: design

#112 Include Categories for companies
  .eleventy.js
  _includes/companylist.njk
  _includes/tagslist.njk
  companies/amazon.md
  companies/amerisource-bergen.md
  companies/anthem.md
  companies/apple.md
  companies/att.md
  companies/bank-of-america.md
  companies/ben-jerrys.md
  companies/berkshire-hathaway.md
  companies/chevron.md
  companies/cisco.md
  companies/comcast.md
  companies/cvs-health.md
  companies/exxon-mobile.md
  companies/fannie-mae.md
  companies/fordmotor.md
  companies/general-motors.md
  companies/github.md
  companies/google.md
  companies/home-depot.md
  companies/kroger.md
  companies/marathon-petroleum.md
  companies/mckesson.md
  companies/microsoft.md
  companies/netflix.md
  companies/phillips-66.md
  companies/playstation.md
  companies/redfin.md
  companies/riot-games.md
  companies/salesforce.md
  companies/slack.md
  companies/square.md
  companies/twilio.md
  companies/unitedhealth-group.md
  companies/usa-softball.md
  companies/walmart.md
  companies/wells-fargo.md
  companies/zillow.md
  examples/add-a-company.md
  statements.njk
  tags.njk
Labels: data collection, design

#113 Add Cigna to companies
  companies/cigna.md
Labels: hacktoberfest-accepted

#115 add realtor.com
  companies/realtor.md
Labels: hacktoberfest-accepted

#118 Add Cardinal Health to companies
  companies/cardinal-health.md
Labels: hacktoberfest-accepted

#116 Add access fund
  companies/access-fund.md
Labels: hacktoberfest-accepted

#119 updated footer
  _includes/layouts/base.njk
  style.css
Labels: design

#120 Design company detail page
  .github/ISSUE_TEMPLATE/company_data.md
  README.md
  _includes/layouts/company.njk
  companies/salesforce.md
  examples/add-a-company.md
  images/salesforce.jpeg
  statement-content.njk
  style.css
Labels: design

#125 add relevant resources
  _includes/layouts/resources.njk
  resources.md
  style.css
Labels: hacktoberfest-accepted

#126 Dates now in UTC time
  .eleventy.js
Labels: bug, hacktoberfest-accepted

#109 New thislinda
  companies/jpmorgan-chase.md
  companies/zoom.md
  package-lock.json
Labels: hacktoberfest-accepted

#134 Added Marvel Studios data
  companies/marvel-studios.md
  images/marvel-studios.jpg
Labels: hacktoberfest-accepted

#148 Added link to resources page to navigation
  _includes/layouts/base.njk
Labels: hacktoberfest-accepted

#142 #138: add pinterest data
  companies/pinterest.md
  images/pinterest.jpg
Labels: hacktoberfest-accepted

#145 #66: add billboard data
  companies/billboard.md
  images/hand-mic-bb10-2020-market-billboard.jpg
Labels: hacktoberfest-accepted

#150 Added resource to resources page
  resources.md
Labels: hacktoberfest-accepted

#151 Added Brown Girls Climb data
  companies/brown-girls-climb.md
  images/brown-girls-climb.png
Labels: hacktoberfest-accepted

#152 Update README.md
  README.md
Labels: hacktoberfest-accepted

#155 Better Visibility for Social Buttons
  _includes/layouts/base.njk
Labels: hacktoberfest-accepted

#156 Set up action-yamllint
  .github/workflows/reviewdog.yml
Labels: hacktoberfest-accepted

#157 Added article to Redfin page
  companies/redfin.md
Labels: hacktoberfest-accepted

#163 Update resources.md
  resources.md
Labels: hacktoberfest-accepted
